using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using EfMigrateHub.Core;

namespace EfMigrateHub.App.ViewModels;

/// <summary>What the detail pane is showing for the selected migration.</summary>
public enum MigrationView
{
    /// <summary>The migration's own <c>.cs</c> file, with its Up and Down methods.</summary>
    Source,

    /// <summary>The SQL this one migration would run, generated by <c>migrations script</c>.</summary>
    Sql,
}

/// <summary>
/// The detail pane beside the migrations list: the selected migration's source, and on request the
/// SQL it produces.
/// </summary>
/// <remarks>
/// The source is a file read, so it happens on selection. The SQL is not — <c>migrations script</c>
/// builds the project, which takes seconds, and arrowing down a list of twenty migrations must not
/// queue twenty builds. So it is behind a button, and once generated it is kept for the session,
/// keyed by migration id. The cache is dropped whenever the migrations list is reloaded, because
/// that is the point at which the files behind it may have changed.
/// </remarks>
public partial class MigrationDetailViewModel : ObservableObject
{
    private readonly CommandSession _session;
    private readonly Func<EfTarget?> _target;
    private readonly Func<IReadOnlyList<MigrationInfo>> _migrations;

    /// <summary>The shared "Idempotent" option from the workspace options pane. See <see cref="ScriptViewModel"/>,
    /// which the flag and its provider gate are shared with.</summary>
    private readonly Func<bool> _idempotentRequested;
    private readonly Func<bool> _canUseIdempotent;
    private readonly Func<Task> _ensureProviderKnownAsync;

    /// <summary>
    /// Generated SQL keyed by migration id and whether it was idempotent, so re-selecting a migration
    /// or flipping the option back costs nothing, and the two never get shown under each other's key.
    /// </summary>
    // ponytail: invalidated by a list refresh, not by watching the files. Add a watcher if editing a
    // migration and re-reading its SQL without refreshing proves confusing.
    private readonly Dictionary<(string Id, bool Idempotent), string> _sqlCache = new();

    public MigrationDetailViewModel(
        CommandSession session,
        Func<EfTarget?> target,
        Func<IReadOnlyList<MigrationInfo>> migrations,
        Func<bool>? idempotentRequested = null,
        Func<bool>? canUseIdempotent = null,
        Func<Task>? ensureProviderKnownAsync = null)
    {
        _session = session;
        _target = target;
        _migrations = migrations;
        _idempotentRequested = idempotentRequested ?? (() => false);
        _canUseIdempotent = canUseIdempotent ?? (() => true);
        _ensureProviderKnownAsync = ensureProviderKnownAsync ?? (() => Task.CompletedTask);

        _session.PropertyChanged += (_, e) =>
        {
            if (e.PropertyName == nameof(CommandSession.IsRunning))
            {
                NotifyCommandStates();
            }
        };
    }

    /// <summary>Supplied by the view: hands a path to the OS to open in whatever owns <c>.cs</c>.</summary>
    public Func<string, Task>? OpenFileAsync { get; set; }

    [ObservableProperty]
    private MigrationRow? _migration;

    [ObservableProperty]
    private MigrationView _view = MigrationView.Source;

    [ObservableProperty]
    private string _source = "";

    [ObservableProperty]
    private string? _sourcePath;

    [ObservableProperty]
    private string _sql = "";

    /// <summary>
    /// Why there is nothing to show — the file could not be found or read. Kept separate from the
    /// text so an empty pane always says why it is empty.
    /// </summary>
    [ObservableProperty]
    private string? _problem;

    public bool HasMigration => Migration is not null;

    public bool IsShowingSql => View == MigrationView.Sql;

    /// <summary>What the editor displays. One editor for both views, so the two cannot disagree.</summary>
    public string Text => IsShowingSql ? Sql : Source;

    public bool HasText => Text.Length > 0;

    /// <summary>
    /// Only worth showing while there is nothing else in the pane. A source file that could not be
    /// read does not stop the SQL being generated, and the explanation must not sit over the SQL.
    /// </summary>
    public bool HasProblem => Problem is not null && !HasText;

    public bool HasSourceFile => SourcePath is not null;

    public string? Subtitle => Migration is null
        ? null
        : IsShowingSql
            ? "SQL for this migration only, generated from the migration before it."
            : SourcePath ?? "Source file not found.";

    public bool IsReady => !_session.IsRunning && _target() is not null;

    /// <summary>The option as it will actually be applied: ticked, and supported by the provider.</summary>
    private bool EffectiveIdempotent => _idempotentRequested() && _canUseIdempotent();

    // ---- Lifecycle ----

    /// <summary>Called when the list selection changes.</summary>
    public void Show(MigrationRow? row)
    {
        Migration = row;
        Problem = null;
        Sql = "";
        Source = "";
        SourcePath = null;

        if (row is null)
        {
            View = MigrationView.Source;
            NotifyCommandStates();
            return;
        }

        LoadSource(row);

        // Staying on the SQL view across a selection change would show an empty pane until the user
        // pressed the button again, so it only holds when this migration's SQL is already generated
        // for the option as currently ticked.
        if (_sqlCache.TryGetValue((row.Id, EffectiveIdempotent), out var cached))
        {
            Sql = cached;
        }
        else if (IsShowingSql)
        {
            View = MigrationView.Source;
        }

        NotifyCommandStates();
    }

    /// <summary>
    /// Drops the generated SQL. Called when the migrations list is reloaded: the files behind it may
    /// have been added, removed or edited, and stale SQL attributed to a migration is worse than
    /// none.
    /// </summary>
    public void InvalidateSql()
    {
        _sqlCache.Clear();
        Sql = "";
        if (IsShowingSql)
        {
            View = MigrationView.Source;
        }
    }

    public void Clear()
    {
        _sqlCache.Clear();
        Migration = null;
        Source = "";
        SourcePath = null;
        Sql = "";
        Problem = null;
        View = MigrationView.Source;
        NotifyCommandStates();
    }

    public void NotifyTargetChanged() => NotifyCommandStates();

    // ---- Commands ----

    [RelayCommand]
    private void ShowSource() => View = MigrationView.Source;

    [RelayCommand(CanExecute = nameof(CanShowSql))]
    private async Task ShowSqlAsync()
    {
        var row = Migration;
        var target = _target();
        if (row is null || target is null)
        {
            return;
        }

        await _ensureProviderKnownAsync();
        var idempotent = EffectiveIdempotent;

        if (_sqlCache.TryGetValue((row.Id, idempotent), out var cached))
        {
            Sql = cached;
            View = MigrationView.Sql;
            return;
        }

        var path = MigrationFiles.ScriptCachePath(target.Project, target.Context, row.Id);

        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            _session.StatusMessage = $"Could not use the temp folder for the preview: {ex.Message}";
            return;
        }

        // "0" is EF's name for the empty database, which is what the first migration starts from.
        var from = PreviousId(row.Id) ?? "0";

        var result = await _session.RunAsync(
            EfArgs.MigrationsScript(target, path, from, row.Id, idempotent),
            $"Generating SQL for '{row.Name}'");

        if (result is null)
        {
            return;
        }

        if (!result.Success)
        {
            _session.ReportFailure(result, $"Could not generate the SQL for '{row.Name}'.");
            return;
        }

        string sql;
        try
        {
            sql = File.ReadAllText(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            _session.StatusMessage = $"The script was written to {path} but could not be read: {ex.Message}";
            return;
        }

        _sqlCache[(row.Id, idempotent)] = sql;
        Sql = sql;
        View = MigrationView.Sql;
        _session.StatusMessage = $"SQL for '{row.Name}': {sql.Length:N0} characters.";
    }

    private bool CanShowSql() => IsReady && HasMigration;

    [RelayCommand(CanExecute = nameof(HasText))]
    private async Task CopyAsync()
    {
        if (_session.CopyToClipboardAsync is null)
        {
            return;
        }

        await _session.CopyToClipboardAsync(Text);
        _session.StatusMessage = IsShowingSql
            ? "SQL copied to the clipboard."
            : "Migration source copied to the clipboard.";
    }

    [RelayCommand(CanExecute = nameof(HasSourceFile))]
    private async Task OpenSourceAsync()
    {
        if (OpenFileAsync is not null && SourcePath is not null)
        {
            await OpenFileAsync(SourcePath);
        }
    }

    // ---- Work ----

    private void LoadSource(MigrationRow row)
    {
        var project = _target()?.Project;
        if (string.IsNullOrWhiteSpace(project))
        {
            Problem = "Select a migrations project to see the migration's source.";
            return;
        }

        var path = MigrationFiles.FindSource(project, row.Id);
        if (path is null)
        {
            Problem =
                $"No file named '{row.Id}.cs' was found in the migrations project. It may live in "
                + "another project, or have been renamed.";
            return;
        }

        try
        {
            Source = File.ReadAllText(path);
            SourcePath = path;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            Problem = $"Could not read {path}: {ex.Message}";
        }
    }

    /// <summary>The migration immediately before this one, or null when it is the first.</summary>
    private string? PreviousId(string id)
    {
        var ordered = _migrations();
        var index = -1;
        for (var i = 0; i < ordered.Count; i++)
        {
            if (string.Equals(ordered[i].Id, id, StringComparison.Ordinal))
            {
                index = i;
                break;
            }
        }

        return index > 0 ? ordered[index - 1].Id : null;
    }

    private void NotifyCommandStates()
    {
        OnPropertyChanged(nameof(IsReady));
        ShowSqlCommand.NotifyCanExecuteChanged();
        CopyCommand.NotifyCanExecuteChanged();
        OpenSourceCommand.NotifyCanExecuteChanged();
    }

    // ---- Property change plumbing ----

    partial void OnMigrationChanged(MigrationRow? value)
    {
        OnPropertyChanged(nameof(HasMigration));
        OnPropertyChanged(nameof(Subtitle));
        NotifyCommandStates();
    }

    partial void OnViewChanged(MigrationView value)
    {
        OnPropertyChanged(nameof(IsShowingSql));
        OnPropertyChanged(nameof(Subtitle));
        NotifyText();
    }

    partial void OnSourceChanged(string value) => NotifyText();

    partial void OnSqlChanged(string value) => NotifyText();

    partial void OnSourcePathChanged(string? value)
    {
        OnPropertyChanged(nameof(HasSourceFile));
        OnPropertyChanged(nameof(Subtitle));
        OpenSourceCommand.NotifyCanExecuteChanged();
    }

    partial void OnProblemChanged(string? value) => OnPropertyChanged(nameof(HasProblem));

    private void NotifyText()
    {
        OnPropertyChanged(nameof(Text));
        OnPropertyChanged(nameof(HasText));
        OnPropertyChanged(nameof(HasProblem));
        CopyCommand.NotifyCanExecuteChanged();
    }
}
